apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# If changing the namespace, also update the cluster_role_binding.yaml.
namespace: default
resources:
- crds/core.observatorium.io_observatoria.yaml
- cluster_role.yaml
- cluster_role_binding.yaml
- service_account.yaml
- operator.yaml
